---
image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test

build_tarball:
  stage: build
  tags:
    - cm-official-docker-executor
  only:
    - devel@f5ansible/f5_modules_collection
  script:
    - pip install ansible
    - ansible-galaxy collection build -p ./builds
  artifacts:
    paths:
      - builds/*.tar.gz

test_tarball:
  stage: test
  tags:
    - cm-official-docker-executor
  only:
    - devel@f5ansible/f5_modules_collection
  dependencies:
    - build_tarball
  script:
    - pip install galaxy-importer
    - export GALAXY_IMPORTER_CONFIG= $CI_PROJECT_DIR/galaxy-importer.cfg
  artifacts:
    when: on_failure
    paths:
      - ./importer_result.json