---
image: python:3.7-alpine

services:
  - docker:dind

stages:
  - build
  - test

build_tarball:
  stage: build
  tags:
    - cm-official-docker-executor
  script:
    - apk add --no-cache build-base
    - pip install ansible
    - ansible-galaxy collection build -p ./builds
  artifacts:
    paths:
      - builds/*.tar.gz

test_tarball:
  stage: test
  tags:
    - cm-official-docker-executor
  dependencies:
    - build_tarball
  script:
    - apk add --no-cache build-base
    - pip install galaxy-importer
    - export GALAXY_IMPORTER_CONFIG= $CI_PROJECT_DIR/galaxy-importer.cfg
  artifacts:
    when: on_failure
    paths:
      - ./importer_result.json